apiVersion: v1
kind: Service
metadata:
  name: nxrm-service
  namespace: default
  labels:
    app: nxrm
spec:
  type: NodePort
  selector:
    app: nxrm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089

